// <auto-generated />
using ControladorAviao.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControladorAviao.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230111230125_Teste")]
    partial class Teste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControladorAviao.Models.AviaoModel", b =>
                {
                    b.Property<int>("aviaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NumeroRegistro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("aviaoId"));

                    b.Property<string>("modelo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Modelo");

                    b.Property<int>("qntdAssentos")
                        .HasColumnType("int")
                        .HasColumnName("QntdAssentos");

                    b.Property<int>("qntdEspeciais")
                        .HasColumnType("int")
                        .HasColumnName("QntdEspeciais");

                    b.HasKey("aviaoId");

                    b.ToTable("Avioes");
                });

            modelBuilder.Entity("ControladorAviao.Models.VooModel", b =>
                {
                    b.Property<int>("nVoo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NumeroVoo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nVoo"));

                    b.Property<int>("aviaoId")
                        .HasColumnType("int");

                    b.Property<string>("data")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("Data");

                    b.Property<string>("horario")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("Horario");

                    b.Property<int>("localChegada")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("LocalChegada");

                    b.Property<string>("localPartida")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("LocalPartida");

                    b.Property<float>("valorEspecial")
                        .HasColumnType("real")
                        .HasColumnName("ValorEspecial");

                    b.Property<float>("valorNormal")
                        .HasColumnType("real")
                        .HasColumnName("ValorNormal");

                    b.HasKey("nVoo");

                    b.HasIndex("aviaoId");

                    b.ToTable("Voos");
                });

            modelBuilder.Entity("ControladorAviao.Models.VooModel", b =>
                {
                    b.HasOne("ControladorAviao.Models.AviaoModel", "aviao")
                        .WithMany("Voos")
                        .HasForeignKey("aviaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aviao");
                });

            modelBuilder.Entity("ControladorAviao.Models.AviaoModel", b =>
                {
                    b.Navigation("Voos");
                });
#pragma warning restore 612, 618
        }
    }
}
